<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\Builder;

use Swaggest\JsonSchema\Constraint\Properties;
use Swaggest\JsonSchema\Schema;
use WordPress\Blueprints\Model\DataClass\InstallPluginStep;
use Swaggest\JsonSchema\Structure\ClassStructureContract;


/**
 * Built from #/definitions/InstallPluginStep
 */
class InstallPluginStepBuilder extends InstallPluginStep implements ClassStructureContract
{
    use \Swaggest\JsonSchema\Structure\ClassStructureTrait;

    /**
     * @param Properties|static $properties
     * @param Schema $ownerSchema
     */
    public static function setUpProperties($properties, Schema $ownerSchema)
    {
        $properties->progress = ProgressBuilder::schema();
        $properties->continueOnError = Schema::boolean();
        $properties->continueOnError->default = false;
        $properties->step = Schema::string();
        $properties->step->description = "The step identifier.";
        $properties->step->const = "installPlugin";
        $properties->pluginZipFile = new Schema();
        $properties->pluginZipFile->anyOf[0] = Schema::string();
        $properties->pluginZipFile->anyOf[1] = FilesystemResourceBuilder::schema();
        $properties->pluginZipFile->anyOf[2] = InlineResourceBuilder::schema();
        $properties->pluginZipFile->anyOf[3] = CoreThemeResourceBuilder::schema();
        $properties->pluginZipFile->anyOf[4] = CorePluginResourceBuilder::schema();
        $properties->pluginZipFile->anyOf[5] = UrlResourceBuilder::schema();
        $properties->pluginZipFile->setFromRef('#/definitions/FileReference');
        $properties->activate = Schema::boolean();
        $properties->activate->description = "Whether to activate the plugin after installing it.";
        $properties->activate->default = true;
        $ownerSchema->type = Schema::OBJECT;
        $ownerSchema->additionalProperties = false;
        $ownerSchema->required = array(
            self::names()->pluginZipFile,
            self::names()->step,
        );
        $ownerSchema->setFromRef('#/definitions/InstallPluginStep');
    }

    /**
     * @param ProgressBuilder $progress
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setProgress(ProgressBuilder $progress)
    {
        $this->progress = $progress;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    /**
     * @param bool $continueOnError
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setContinueOnError($continueOnError)
    {
        $this->continueOnError = $continueOnError;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    /**
     * @param string $step The step identifier.
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setStep($step)
    {
        $this->step = $step;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    /**
     * @param string|FilesystemResourceBuilder|InlineResourceBuilder|CoreThemeResourceBuilder|CorePluginResourceBuilder|UrlResourceBuilder $pluginZipFile
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setPluginZipFile($pluginZipFile)
    {
        $this->pluginZipFile = $pluginZipFile;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    /**
     * @param bool $activate Whether to activate the plugin after installing it.
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setActivate($activate)
    {
        $this->activate = $activate;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    function toDataObject()
    {
        $dataObject = new InstallPluginStep();
        $dataObject->progress = $this->recursiveJsonSerialize($this->progress);
        $dataObject->continueOnError = $this->recursiveJsonSerialize($this->continueOnError);
        $dataObject->step = $this->recursiveJsonSerialize($this->step);
        $dataObject->pluginZipFile = $this->recursiveJsonSerialize($this->pluginZipFile);
        $dataObject->activate = $this->recursiveJsonSerialize($this->activate);
        return $dataObject;
    }

    /**
     * @param mixed $objectMaybe
     */
    private function recursiveJsonSerialize($objectMaybe)
    {
        if ( is_array( $objectMaybe ) ) {
        	return array_map([$this, 'recursiveJsonSerialize'], $objectMaybe);
        } elseif ( $objectMaybe instanceof \Swaggest\JsonSchema\Structure\ClassStructureContract ) {
        	return $objectMaybe->toDataObject();
        } else {
        	return $objectMaybe;
        }
    }
}