<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\Progress;


class ValidRunPHPStep
{
    const SLUG = 'runPHP';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string The step identifier. */
    public $step = 'runPHP';

    /** @var string The PHP code to run. */
    public $code;

    /**
     * @param string $code The PHP code to run.
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct($code, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->code = $code;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}