<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;



class ValidUrlResource
{
    const SLUG = 'url';

    /** @var string Identifies the file resource as a URL */
    public $resource = 'url';

    /** @var string The URL of the file */
    public $url;

    /** @var string Optional caption for displaying a progress message */
    public $caption;

    /**
     * @param string $url The URL of the file
     * @param string $caption Optional caption for displaying a progress message
     */
    function __construct($url, $caption = NULL)
    {
        $this->url = $url;
        $this->caption = $caption;
    }
}