<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;



class ValidWordPressInstallationOptions
{
    /** @var string */
    public $adminUsername = 'admin';

    /** @var string */
    public $adminPassword = 'password';

    /**
     * @param string $adminUsername
     * @param string $adminPassword
     */
    function __construct($adminUsername = NULL, $adminPassword = NULL)
    {
        $this->adminUsername = $adminUsername;
        $this->adminPassword = $adminPassword;
    }
}