<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;



class ValidProgress
{
    /** @var float */
    public $weight;

    /** @var string */
    public $caption;

    /**
     * @param float $weight
     * @param string $caption
     */
    function __construct($weight = NULL, $caption = NULL)
    {
        $this->weight = $weight;
        $this->caption = $caption;
    }
}