<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;



class ValidBlueprintOnBoot
{
    /** @var string The URL to navigate to after the blueprint has been run. */
    public $openUrl;

    /** @var bool */
    public $login;

    /**
     * @param string $openUrl The URL to navigate to after the blueprint has been run.
     * @param bool $login
     */
    function __construct($openUrl = NULL, $login = NULL)
    {
        $this->openUrl = $openUrl;
        $this->login = $login;
    }
}