<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\Progress;


class ValidMkdirStep
{
    const SLUG = 'mkdir';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string */
    public $step = 'mkdir';

    /** @var string The path of the directory you want to create */
    public $path;

    /**
     * @param string $path The path of the directory you want to create
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct($path, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->path = $path;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}