<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\Progress;
use WordPress\Blueprints\Model\Dirty\WordPressInstallationOptions;


class ValidRunWordPressInstallerStep
{
    const SLUG = 'runWpInstallationWizard';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string */
    public $step = 'runWpInstallationWizard';

    /** @var WordPressInstallationOptions */
    public $options;

    /**
     * @param WordPressInstallationOptions $options
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct(WordPressInstallationOptions $options, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->options = $options;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}