<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\CorePluginResource;
use WordPress\Blueprints\Model\Dirty\CoreThemeResource;
use WordPress\Blueprints\Model\Dirty\FilesystemResource;
use WordPress\Blueprints\Model\Dirty\InlineResource;
use WordPress\Blueprints\Model\Dirty\Progress;
use WordPress\Blueprints\Model\Dirty\UrlResource;


class ValidInstallSqliteIntegrationStep
{
    const SLUG = 'installSqliteIntegration';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string */
    public $step = 'installSqliteIntegration';

    /** @var string|FilesystemResource|InlineResource|CoreThemeResource|CorePluginResource|UrlResource */
    public $sqlitePluginZip;

    /**
     * @param string|FilesystemResource|InlineResource|CoreThemeResource|CorePluginResource|UrlResource $sqlitePluginZip
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct($sqlitePluginZip, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->sqlitePluginZip = $sqlitePluginZip;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}