<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\Progress;


class ValidDefineWpConfigConstsStep
{
    const SLUG = 'defineWpConfigConsts';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string */
    public $step = 'defineWpConfigConsts';

    /** @var array The constants to define */
    public $consts;

    /**
     * @param array $consts The constants to define
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct($consts, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->consts = $consts;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}