<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\Progress;


class ValidSetSiteOptionsStep
{
    const SLUG = 'setSiteOptions';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string The name of the step. Must be "setSiteOptions". */
    public $step = 'setSiteOptions';

    /** @var array The options to set on the site. */
    public $options;

    /**
     * @param array $options The options to set on the site.
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct($options, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->options = $options;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}