<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\Progress;


class ValidEnableMultisiteStep
{
    const SLUG = 'enableMultisite';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string */
    public $step = 'enableMultisite';

    /**
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct(Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}