<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\CorePluginResource;
use WordPress\Blueprints\Model\Dirty\CoreThemeResource;
use WordPress\Blueprints\Model\Dirty\FilesystemResource;
use WordPress\Blueprints\Model\Dirty\InlineResource;
use WordPress\Blueprints\Model\Dirty\Progress;
use WordPress\Blueprints\Model\Dirty\UrlResource;


class ValidUnzipStep
{
    const SLUG = 'unzip';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string */
    public $step = 'unzip';

    /** @var string|FilesystemResource|InlineResource|CoreThemeResource|CorePluginResource|UrlResource */
    public $zipFile;

    /** @var string The path to extract the zip file to */
    public $extractToPath;

    /**
     * @param string|FilesystemResource|InlineResource|CoreThemeResource|CorePluginResource|UrlResource $zipFile
     * @param string $extractToPath The path to extract the zip file to
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct($zipFile, $extractToPath, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->zipFile = $zipFile;
        $this->extractToPath = $extractToPath;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}