<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\CorePluginResource;
use WordPress\Blueprints\Model\Dirty\CoreThemeResource;
use WordPress\Blueprints\Model\Dirty\FilesystemResource;
use WordPress\Blueprints\Model\Dirty\InlineResource;
use WordPress\Blueprints\Model\Dirty\Progress;
use WordPress\Blueprints\Model\Dirty\UrlResource;


class ValidInstallPluginStep
{
    const SLUG = 'installPlugin';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string The step identifier. */
    public $step = 'installPlugin';

    /** @var string|FilesystemResource|InlineResource|CoreThemeResource|CorePluginResource|UrlResource */
    public $pluginZipFile;

    /** @var bool Whether to activate the plugin after installing it. */
    public $activate = true;

    /**
     * @param string|FilesystemResource|InlineResource|CoreThemeResource|CorePluginResource|UrlResource $pluginZipFile
     * @param bool $activate Whether to activate the plugin after installing it.
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct($pluginZipFile, $activate = NULL, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->pluginZipFile = $pluginZipFile;
        $this->activate = $activate;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}