<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\Progress;


class ValidWPCLIStep
{
    const SLUG = 'wp-cli';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string The step identifier. */
    public $step = 'wp-cli';

    /** @var string[]|array The WP CLI command to run. */
    public $command;

    /**
     * @param string[]|array $command The WP CLI command to run.
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct($command, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->command = $command;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}