<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\CorePluginResource;
use WordPress\Blueprints\Model\Dirty\CoreThemeResource;
use WordPress\Blueprints\Model\Dirty\FilesystemResource;
use WordPress\Blueprints\Model\Dirty\InlineResource;
use WordPress\Blueprints\Model\Dirty\Progress;
use WordPress\Blueprints\Model\Dirty\UrlResource;


class ValidWriteFileStep
{
    const SLUG = 'writeFile';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string */
    public $step = 'writeFile';

    /** @var string The path of the file to write to */
    public $path;

    /** @var string|FilesystemResource|InlineResource|CoreThemeResource|CorePluginResource|UrlResource|string The data to write */
    public $data;

    /**
     * @param string $path The path of the file to write to
     * @param string|FilesystemResource|InlineResource|CoreThemeResource|CorePluginResource|UrlResource|string $data The data to write
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct($path, $data, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->path = $path;
        $this->data = $data;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}