<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;



class ValidInlineResource
{
    const SLUG = 'inline';

    /** @var string Identifies the file resource as an inline string */
    public $resource = 'inline';

    /** @var string The contents of the file */
    public $contents;

    /**
     * @param string $contents The contents of the file
     */
    function __construct($contents)
    {
        $this->contents = $contents;
    }
}