<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;



class ValidFilesystemResource
{
    const SLUG = 'filesystem';

    /** @var string Identifies the file resource as Virtual File System (VFS) */
    public $resource = 'filesystem';

    /** @var string The path to the file in the VFS */
    public $path;

    /**
     * @param string $path The path to the file in the VFS
     */
    function __construct($path)
    {
        $this->path = $path;
    }
}