<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\Progress;


class ValidMvStep
{
    const SLUG = 'mv';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string */
    public $step = 'mv';

    /** @var string Source path */
    public $fromPath;

    /** @var string Target path */
    public $toPath;

    /**
     * @param string $fromPath Source path
     * @param string $toPath Target path
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct($fromPath, $toPath, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->fromPath = $fromPath;
        $this->toPath = $toPath;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}