<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\Progress;


class ValidActivateThemeStep
{
    const SLUG = 'activateTheme';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string */
    public $step = 'activateTheme';

    /** @var string Theme slug, like 'twentytwentythree'. */
    public $slug;

    /**
     * @param string $slug Theme slug, like 'twentytwentythree'.
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct($slug, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->slug = $slug;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}