<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\Progress;


/**
 * @property mixed $callback The PHP function.
 */
class ValidEvalPHPCallbackStep
{
    const SLUG = 'evalPHPCallback';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string The step identifier. */
    public $step = 'evalPHPCallback';

    /**
     * @param mixed $callback The PHP function.
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct($callback, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->callback = $callback;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}