<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\InternalValidated;

use WordPress\Blueprints\Model\Dirty\Progress;


class ValidDefineSiteUrlStep
{
    const SLUG = 'defineSiteUrl';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string */
    public $step = 'defineSiteUrl';

    /** @var string The URL */
    public $siteUrl;

    /**
     * @param string $siteUrl The URL
     * @param Progress $progress
     * @param bool $continueOnError
     */
    function __construct($siteUrl, Progress $progress = NULL, $continueOnError = NULL)
    {
        $this->siteUrl = $siteUrl;
        $this->progress = $progress;
        $this->continueOnError = $continueOnError;
    }
}