<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\Dirty;

use Swaggest\JsonSchema\Constraint\Properties;
use Swaggest\JsonSchema\Schema;
use Swaggest\JsonSchema\Structure\ClassStructure;
use Swaggest\JsonSchema\Structure\ClassStructureContract;


class BlueprintOnBoot extends ClassStructure implements ClassStructureContract
{
    use \Swaggest\JsonSchema\Structure\ClassStructureTrait;

    /** @var string The URL to navigate to after the blueprint has been run. */
    public $openUrl;

    /** @var bool */
    public $login;

    /**
     * @param Properties|static $properties
     * @param Schema $ownerSchema
     */
    public static function setUpProperties($properties, Schema $ownerSchema)
    {
        $properties->openUrl = Schema::string();
        $properties->openUrl->description = "The URL to navigate to after the blueprint has been run.";
        $properties->login = Schema::boolean();
        $ownerSchema->type = Schema::OBJECT;
        $ownerSchema->additionalProperties = false;
    }

    /**
     * @param string $openUrl The URL to navigate to after the blueprint has been run.
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setOpenUrl($openUrl)
    {
        $this->openUrl = $openUrl;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    /**
     * @param bool $login
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setLogin($login)
    {
        $this->login = $login;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    static function create()
    {
        return new static();
    }

    function normalize()
    {
        return new \WordPress\Blueprints\Model\InternalValidated\ValidBlueprintOnBoot(
        $this->openUrl,
        $this->login
        );
    }

    /**
     * @param mixed $objectMaybe
     */
    private function recursiveJsonSerialize($objectMaybe)
    {
        if ( is_array( $objectMaybe ) ) {
        	return array_map([$this, 'recursiveJsonSerialize'], $objectMaybe);
        } elseif ( $objectMaybe instanceof \Swaggest\JsonSchema\Structure\ClassStructureContract ) {
        	return $objectMaybe->normalize();
        } else {
        	return $objectMaybe;
        }
    }
}