<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\Dirty;

use Swaggest\JsonSchema\Constraint\Properties;
use Swaggest\JsonSchema\Schema;
use Swaggest\JsonSchema\Structure\ClassStructure;
use Swaggest\JsonSchema\Structure\ClassStructureContract;


/**
 * Built from #/definitions/InstallThemeStep
 */
class InstallThemeStep extends ClassStructure implements ClassStructureContract
{
    use \Swaggest\JsonSchema\Structure\ClassStructureTrait;

    const SLUG = 'installTheme';

    /** @var Progress */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string The step identifier. */
    public $step = 'installTheme';

    /** @var string|FilesystemResource|InlineResource|CoreThemeResource|CorePluginResource|UrlResource */
    public $themeZipFile;

    /** @var bool Whether to activate the theme after installing it. */
    public $activate = true;

    /**
     * @param Properties|static $properties
     * @param Schema $ownerSchema
     */
    public static function setUpProperties($properties, Schema $ownerSchema)
    {
        $properties->progress = Progress::schema();
        $properties->continueOnError = Schema::boolean();
        $properties->continueOnError->default = false;
        $properties->step = Schema::string();
        $properties->step->description = "The step identifier.";
        $properties->step->const = "installTheme";
        $properties->themeZipFile = new Schema();
        $properties->themeZipFile->anyOf[0] = Schema::string();
        $properties->themeZipFile->anyOf[1] = FilesystemResource::schema();
        $properties->themeZipFile->anyOf[2] = InlineResource::schema();
        $properties->themeZipFile->anyOf[3] = CoreThemeResource::schema();
        $properties->themeZipFile->anyOf[4] = CorePluginResource::schema();
        $properties->themeZipFile->anyOf[5] = UrlResource::schema();
        $properties->themeZipFile->setFromRef('#/definitions/FileReference');
        $properties->activate = Schema::boolean();
        $properties->activate->description = "Whether to activate the theme after installing it.";
        $properties->activate->default = true;
        $ownerSchema->type = Schema::OBJECT;
        $ownerSchema->additionalProperties = false;
        $ownerSchema->required = array(
            self::names()->step,
            self::names()->themeZipFile,
        );
        $ownerSchema->setFromRef('#/definitions/InstallThemeStep');
    }

    /**
     * @param Progress $progress
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setProgress(Progress $progress)
    {
        $this->progress = $progress;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    /**
     * @param bool $continueOnError
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setContinueOnError($continueOnError)
    {
        $this->continueOnError = $continueOnError;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    /**
     * @param string $step The step identifier.
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setStep($step)
    {
        $this->step = $step;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    /**
     * @param string|FilesystemResource|InlineResource|CoreThemeResource|CorePluginResource|UrlResource $themeZipFile
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setThemeZipFile($themeZipFile)
    {
        $this->themeZipFile = $themeZipFile;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    /**
     * @param bool $activate Whether to activate the theme after installing it.
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setActivate($activate)
    {
        $this->activate = $activate;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    static function create()
    {
        return new static();
    }

    function normalize()
    {
        return new \WordPress\Blueprints\Model\InternalValidated\ValidInstallThemeStep(
        $this->themeZipFile,
        $this->activate,
        $this->progress,
        $this->continueOnError
        );
    }

    /**
     * @param mixed $objectMaybe
     */
    private function recursiveJsonSerialize($objectMaybe)
    {
        if ( is_array( $objectMaybe ) ) {
        	return array_map([$this, 'recursiveJsonSerialize'], $objectMaybe);
        } elseif ( $objectMaybe instanceof \Swaggest\JsonSchema\Structure\ClassStructureContract ) {
        	return $objectMaybe->normalize();
        } else {
        	return $objectMaybe;
        }
    }
}