<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\Dirty;

use Swaggest\JsonSchema\Constraint\Properties;
use Swaggest\JsonSchema\Schema;
use Swaggest\JsonSchema\Structure\ClassStructure;
use Swaggest\JsonSchema\Structure\ClassStructureContract;


/**
 * Built from #/definitions/UrlResource
 */
class UrlResource extends ClassStructure implements ClassStructureContract
{
    use \Swaggest\JsonSchema\Structure\ClassStructureTrait;

    const SLUG = 'url';

    /** @var string Identifies the file resource as a URL */
    public $resource = 'url';

    /** @var string The URL of the file */
    public $url;

    /** @var string Optional caption for displaying a progress message */
    public $caption;

    /**
     * @param Properties|static $properties
     * @param Schema $ownerSchema
     */
    public static function setUpProperties($properties, Schema $ownerSchema)
    {
        $properties->resource = Schema::string();
        $properties->resource->description = "Identifies the file resource as a URL";
        $properties->resource->const = "url";
        $properties->url = Schema::string();
        $properties->url->description = "The URL of the file";
        $properties->caption = Schema::string();
        $properties->caption->description = "Optional caption for displaying a progress message";
        $ownerSchema->type = Schema::OBJECT;
        $ownerSchema->additionalProperties = false;
        $ownerSchema->required = array(
            self::names()->resource,
            self::names()->url,
        );
        $ownerSchema->setFromRef('#/definitions/UrlResource');
    }

    /**
     * @param string $resource Identifies the file resource as a URL
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setResource($resource)
    {
        $this->resource = $resource;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    /**
     * @param string $url The URL of the file
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setUrl($url)
    {
        $this->url = $url;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    /**
     * @param string $caption Optional caption for displaying a progress message
     * @return $this
     * @codeCoverageIgnoreStart
     */
    public function setCaption($caption)
    {
        $this->caption = $caption;
        return $this;
    }
    /** @codeCoverageIgnoreEnd */

    static function create()
    {
        return new static();
    }

    function normalize()
    {
        return new \WordPress\Blueprints\Model\InternalValidated\ValidUrlResource(
        $this->url,
        $this->caption
        );
    }

    /**
     * @param mixed $objectMaybe
     */
    private function recursiveJsonSerialize($objectMaybe)
    {
        if ( is_array( $objectMaybe ) ) {
        	return array_map([$this, 'recursiveJsonSerialize'], $objectMaybe);
        } elseif ( $objectMaybe instanceof \Swaggest\JsonSchema\Structure\ClassStructureContract ) {
        	return $objectMaybe->normalize();
        } else {
        	return $objectMaybe;
        }
    }
}