<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;

use WordPress\Blueprints\Model\Builder\ActivatePluginStepBuilder;
use WordPress\Blueprints\Model\Builder\ActivateThemeStepBuilder;
use WordPress\Blueprints\Model\Builder\BlueprintOnBootBuilder;
use WordPress\Blueprints\Model\Builder\BlueprintSiteOptionsBuilder;
use WordPress\Blueprints\Model\Builder\CorePluginResourceBuilder;
use WordPress\Blueprints\Model\Builder\CoreThemeResourceBuilder;
use WordPress\Blueprints\Model\Builder\CpStepBuilder;
use WordPress\Blueprints\Model\Builder\DefineSiteUrlStepBuilder;
use WordPress\Blueprints\Model\Builder\DefineWpConfigConstsStepBuilder;
use WordPress\Blueprints\Model\Builder\EnableMultisiteStepBuilder;
use WordPress\Blueprints\Model\Builder\EvalPHPCallbackStepBuilder;
use WordPress\Blueprints\Model\Builder\FilesystemResourceBuilder;
use WordPress\Blueprints\Model\Builder\ImportFileStepBuilder;
use WordPress\Blueprints\Model\Builder\InitializeWordPressStepBuilder;
use WordPress\Blueprints\Model\Builder\InlineResourceBuilder;
use WordPress\Blueprints\Model\Builder\InstallPluginStepBuilder;
use WordPress\Blueprints\Model\Builder\InstallSqliteIntegrationStepBuilder;
use WordPress\Blueprints\Model\Builder\InstallThemeStepBuilder;
use WordPress\Blueprints\Model\Builder\MkdirStepBuilder;
use WordPress\Blueprints\Model\Builder\MvStepBuilder;
use WordPress\Blueprints\Model\Builder\RmDirStepBuilder;
use WordPress\Blueprints\Model\Builder\RmStepBuilder;
use WordPress\Blueprints\Model\Builder\RunPHPStepBuilder;
use WordPress\Blueprints\Model\Builder\RunSQLStepBuilder;
use WordPress\Blueprints\Model\Builder\RunWordPressInstallerStepBuilder;
use WordPress\Blueprints\Model\Builder\SetSiteOptionsStepBuilder;
use WordPress\Blueprints\Model\Builder\UnzipStepBuilder;
use WordPress\Blueprints\Model\Builder\UrlResourceBuilder;
use WordPress\Blueprints\Model\Builder\WPCLIStepBuilder;
use WordPress\Blueprints\Model\Builder\WriteFileStepBuilder;


class Blueprint
{
    /** @var string Optional description. It doesn't do anything but is exposed as a courtesy to developers who may want to document which blueprint file does what. */
    public $description;

    /** @var mixed Slot for runtime–specific options, schema must be provided by the runtime. */
    public $runtime;

    /** @var BlueprintOnBootBuilder */
    public $onBoot;

    /** @var string The preferred WordPress version to use. If not specified, the latest supported version will be used */
    public $wpVersion;

    /** @var string[] PHP Constants to define on every request */
    public $constants;

    /** @var string[]|string[]|FilesystemResourceBuilder[]|InlineResourceBuilder[]|CoreThemeResourceBuilder[]|CorePluginResourceBuilder[]|UrlResourceBuilder[]|array WordPress plugins to install and activate */
    public $plugins;

    /** @var BlueprintSiteOptionsBuilder|string[] WordPress site options to define */
    public $siteOptions;

    /** @var ActivatePluginStepBuilder[]|ActivateThemeStepBuilder[]|CpStepBuilder[]|DefineWpConfigConstsStepBuilder[]|DefineSiteUrlStepBuilder[]|EnableMultisiteStepBuilder[]|EvalPHPCallbackStepBuilder[]|ImportFileStepBuilder[]|InstallPluginStepBuilder[]|InstallThemeStepBuilder[]|MkdirStepBuilder[]|MvStepBuilder[]|RmStepBuilder[]|RmDirStepBuilder[]|RunPHPStepBuilder[]|RunWordPressInstallerStepBuilder[]|RunSQLStepBuilder[]|SetSiteOptionsStepBuilder[]|UnzipStepBuilder[]|InitializeWordPressStepBuilder[]|InstallSqliteIntegrationStepBuilder[]|WriteFileStepBuilder[]|WPCLIStepBuilder[]|array The steps to run after every other operation in this Blueprint was executed. */
    public $steps;

    /** @var string */
    public $schema;
}