<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;

use WordPress\Blueprints\Model\Builder\ActivatePluginStepBuilder;
use WordPress\Blueprints\Model\Builder\ActivateThemeStepBuilder;
use WordPress\Blueprints\Model\Builder\BlueprintFeaturesBuilder;
use WordPress\Blueprints\Model\Builder\BlueprintPreferredVersionsBuilder;
use WordPress\Blueprints\Model\Builder\BlueprintSiteOptionsBuilder;
use WordPress\Blueprints\Model\Builder\CorePluginReferenceBuilder;
use WordPress\Blueprints\Model\Builder\CoreThemeReferenceBuilder;
use WordPress\Blueprints\Model\Builder\CpStepBuilder;
use WordPress\Blueprints\Model\Builder\DefineSiteUrlStepBuilder;
use WordPress\Blueprints\Model\Builder\DefineWpConfigConstsStepBuilder;
use WordPress\Blueprints\Model\Builder\EnableMultisiteStepBuilder;
use WordPress\Blueprints\Model\Builder\ImportFileStepBuilder;
use WordPress\Blueprints\Model\Builder\InstallPluginStepBuilder;
use WordPress\Blueprints\Model\Builder\InstallThemeStepBuilder;
use WordPress\Blueprints\Model\Builder\LiteralReferenceBuilder;
use WordPress\Blueprints\Model\Builder\MkdirStepBuilder;
use WordPress\Blueprints\Model\Builder\MvStepBuilder;
use WordPress\Blueprints\Model\Builder\RmDirStepBuilder;
use WordPress\Blueprints\Model\Builder\RmStepBuilder;
use WordPress\Blueprints\Model\Builder\RunPHPStepBuilder;
use WordPress\Blueprints\Model\Builder\RunSQLStepBuilder;
use WordPress\Blueprints\Model\Builder\RunWordPressInstallerStepBuilder;
use WordPress\Blueprints\Model\Builder\SetSiteOptionsStepBuilder;
use WordPress\Blueprints\Model\Builder\UnzipStepBuilder;
use WordPress\Blueprints\Model\Builder\UrlReferenceBuilder;
use WordPress\Blueprints\Model\Builder\VFSReferenceBuilder;
use WordPress\Blueprints\Model\Builder\WPCLIStepBuilder;
use WordPress\Blueprints\Model\Builder\WriteFileStepBuilder;


class Blueprint
{
    /** @var string The URL to navigate to after the blueprint has been run. */
    public $landingPage;

    /** @var string Optional description. It doesn't do anything but is exposed as a courtesy to developers who may want to document which blueprint file does what. */
    public $description;

    /** @var BlueprintPreferredVersionsBuilder The preferred PHP and WordPress versions to use. */
    public $preferredVersions;

    /** @var BlueprintFeaturesBuilder */
    public $features;

    /** @var string[] PHP Constants to define on every request */
    public $constants;

    /** @var string[]|string[]|VFSReferenceBuilder[]|LiteralReferenceBuilder[]|CoreThemeReferenceBuilder[]|CorePluginReferenceBuilder[]|UrlReferenceBuilder[]|array WordPress plugins to install and activate */
    public $plugins;

    /** @var BlueprintSiteOptionsBuilder|string[] WordPress site options to define */
    public $siteOptions;

    /** @var string[]|array The PHP extensions to use. */
    public $phpExtensionBundles;

    /** @var ActivatePluginStepBuilder[]|ActivateThemeStepBuilder[]|CpStepBuilder[]|DefineWpConfigConstsStepBuilder[]|DefineSiteUrlStepBuilder[]|EnableMultisiteStepBuilder[]|ImportFileStepBuilder[]|InstallPluginStepBuilder[]|InstallThemeStepBuilder[]|MkdirStepBuilder[]|MvStepBuilder[]|RmStepBuilder[]|RmDirStepBuilder[]|RunPHPStepBuilder[]|RunWordPressInstallerStepBuilder[]|RunSQLStepBuilder[]|SetSiteOptionsStepBuilder[]|UnzipStepBuilder[]|WriteFileStepBuilder[]|WPCLIStepBuilder[]|string[]|mixed[]|bool[]|null[]|array The steps to run after every other operation in this Blueprint was executed. */
    public $steps;

    /** @var string */
    public $schema;
}