<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;



class BlueprintFeatures
{
    /** @var bool Should boot with support for network request via wp_safe_remote_get? */
    public $networking;
}