<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;



class BlueprintOnBoot
{
    /** @var string The URL to navigate to after the blueprint has been run. */
    public $openUrl;

    /** @var bool */
    public $login;
}