<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;



class BlueprintPreferredVersions
{
    /** @var string The preferred PHP version to use. If not specified, the latest supported version will be used */
    public $php;

    /** @var string The preferred WordPress version to use. If not specified, the latest supported version will be used */
    public $wp;
}