<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;



class CorePluginResource implements FileReferenceInterface
{
    /** @var string Identifies the file resource as a WordPress Core plugin */
    public $resource = 'wordpress.org/plugins';

    /** @var string The slug of the WordPress Core plugin */
    public $slug;
}