<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;



class CoreThemeResource implements FileReferenceInterface
{
    const SLUG = 'wordpress.org/themes';

    /** @var string Identifies the file resource as a WordPress Core theme */
    public $resource = 'wordpress.org/themes';

    /** @var string The slug of the WordPress Core theme */
    public $slug;
}