<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;

use WordPress\Blueprints\Model\Builder\FileInfoDataBufferBuilder;


class FileInfoData
{
    /** @var float */
    public $bYTESPERELEMENT;

    /** @var FileInfoDataBufferBuilder */
    public $buffer;

    /** @var float */
    public $byteLength;

    /** @var float */
    public $byteOffset;

    /** @var float */
    public $length;
}