<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;

use WordPress\Blueprints\Model\Builder\FileInfoDataBuilder;


class FileInfo
{
    /** @var string */
    public $key;

    /** @var string */
    public $name;

    /** @var string */
    public $type;

    /** @var FileInfoDataBuilder|float[] */
    public $data;
}