<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;



class InlineResource implements FileReferenceInterface
{
    const SLUG = 'inline';

    /** @var string Identifies the file resource as an inline string */
    public $resource = 'inline';

    /** @var string The contents of the file */
    public $contents;
}