<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;



class InstallPluginOptions
{
    /** @var bool Whether to activate the plugin after installing it. */
    public $activate;
}