<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;


class InstallPluginStep implements StepInterface {
	const SLUG = 'installPlugin';

	/** @var Progress */
	public $progress;

	/** @var bool */
	public $continueOnError = false;

	/** @var string The step identifier. */
	public $step = 'installPlugin';

	/** @var FileReferenceInterface */
	public $pluginZipFile;

	/** @var bool Whether to activate the plugin after installing it. */
	public $activate = true;
}
