<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;



class LiteralReference implements FileReferenceInterface
{
    /** @var string Identifies the file resource as a literal file */
    public $resource = 'literal';

    /** @var string The contents of the file */
    public $contents;
}