<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;

use WordPress\Blueprints\Model\Builder\ProgressBuilder;


class MvStep implements StepInterface
{
    const SLUG = 'mv';

    /** @var ProgressBuilder */
    public $progress;

    /** @var bool */
    public $continueOnError = false;

    /** @var string */
    public $step = 'mv';

    /** @var string Source path */
    public $fromPath;

    /** @var string Target path */
    public $toPath;
}