<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;



class PHPRequestFilesAdditionalProperties
{
    /** @var float */
    public $size;

    /** @var string */
    public $type;

    /** @var float */
    public $lastModified;

    /** @var string */
    public $name;

    /** @var string */
    public $webkitRelativePath;
}