<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;

use WordPress\Blueprints\Model\Builder\PHPRequestBuilder;
use WordPress\Blueprints\Model\Builder\ProgressBuilder;


class PHPRequestStep
{
    /** @var ProgressBuilder */
    public $progress;

    /** @var bool */
    public $continueOnError;

    /** @var string */
    public $step = 'request';

    /** @var PHPRequestBuilder */
    public $request;
}