<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;



class Progress
{
    /** @var float */
    public $weight;

    /** @var string */
    public $caption;
}