<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;

use WordPress\Blueprints\Model\Builder\ProgressBuilder;


class RunPHPStep implements StepInterface
{
    const SLUG = 'runPHP';

    /** @var ProgressBuilder */
    public $progress;

    /** @var bool */
    public $continueOnError;

    /** @var string The step identifier. */
    public $step = 'runPHP';

    /** @var string The PHP code to run. */
    public $code;
}