<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;

use WordPress\Blueprints\Model\Builder\ProgressBuilder;


class SetPHPIniEntryStep
{
    /** @var ProgressBuilder */
    public $progress;

    /** @var bool */
    public $continueOnError;

    /** @var string */
    public $step = 'setPhpIniEntry';

    /** @var string Entry name e.g. "display_errors" */
    public $key;

    /** @var string Entry value as a string e.g. "1" */
    public $value;
}