<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;

use WordPress\Blueprints\Model\Builder\ProgressBuilder;


class SetSiteOptionsStep implements StepInterface
{
    const SLUG = 'setSiteOptions';

    /** @var ProgressBuilder */
    public $progress;

    /** @var bool */
    public $continueOnError;

    /** @var string The name of the step. Must be "setSiteOptions". */
    public $step = 'setSiteOptions';

    /** @var array The options to set on the site. */
    public $options;
}