<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;



class UrlReference implements FileReferenceInterface
{
    /** @var string Identifies the file resource as a URL */
    public $resource = 'url';

    /** @var string The URL of the file */
    public $url;

    /** @var string Optional caption for displaying a progress message */
    public $caption;
}