<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;



class VFSReference implements FileReferenceInterface
{
    /** @var string Identifies the file resource as Virtual File System (VFS) */
    public $resource = 'vfs';

    /** @var string The path to the file in the VFS */
    public $path;
}