<?php
/**
 * @file AUTOGENERATED FILE – DO NOT CHANGE MANUALLY
 * All your changes will get overridden. See the README for more details.
 */

namespace WordPress\Blueprints\Model\DataClass;



class WordPressInstallationOptions
{
    /** @var string */
    public $adminUsername;

    /** @var string */
    public $adminPassword;
}